### ISSUE TITLE
how to draw a mouse on the screen

### ISSUE THREAD

**Issue by parai** [lvgl/lvgl#267] opened 2018-06-04 14:08 UTC
Hi kisvegabor:
This is really a great  project, now I am trying to integrated it with my automotive project https://github.com/parai/as which is by default running on arm qemu. Now I have the display and mouse driver ready, but the mouse cursor doesn't show on the window, so I don't know where the mouse is, in fact from the log I can see the X,Y position but it's not friendly.

Could you hint me how to add a mouse cursor to be displayed on top of the windows?

![screenshot from 2018-06-04 22-00-15](https://user-images.githubusercontent.com/3183386/40921708-d0f4a370-6842-11e8-92c9-317fd0564750.png)
ON              :pressed @(398,236)
ON              :pressed @(319,288)
ON              :pressed @(261,438)
ON              :pressed @(222,327)
ON              :pressed @(48,358)
ON              :pressed @(21,419)
ON              :pressed @(151,465)
ON              :pressed @(325,461)

**Comment by kisvegabor** [comment] 2018-06-04 18:52
Hi,

You can add a cursor with `void lv_indev_set_cursor(lv_indev_t *indev, lv_obj_t *cur_obj)`.
A cursor can be any object. For test I suggest to create a label with a short text, e.g. "<" but later an lv_img object should be used.

Side note:  
As the default button colors in the library are blueish and if you didn't modified the basic styles then I suspect that  you have an ABGR color coding  instead of ARGB (default in LittelvGL). If this is the case then you can swap the bytes in lv_color.h

**Comment by parai** [comment] 2018-06-05 13:28
Hi kisvegabor:
Thanks for you kelp, it works very well.

Next, I think I need to fix the ARGB issue.

**Comment by kisvegabor** [comment] 2018-06-05 13:58
Great! Your welcome!

**Comment by misterbinny** [comment] 2018-07-29 22:56
the lv_layer_sys() and lv_layer_top() functions don't seem to actually draw any of the objects when they're assigned to this layer. You will not see a mouse cursor unless you edit the lv_indev_set_cursor function in lv_indev.c and change the screen pointer to lv_scr_act() for the cursor object.


From: 

lv_obj_set_parent(indev->cursor, lv_layer_sys()  );

To:
lv_obj_set_parent(indev->cursor, lv_scr_act()  );

This can be confirmed with a simple test of assigning a drawn object to lv_layer_sys() or lv_layer_top(); 
Perhaps I've seriously misunderstood the API. 

The code for your input device should be something like: 


	    lv_indev_drv_init(&indev_drv);         //driver type
	    indev_drv.type = LV_INDEV_TYPE_POINTER;  //pointer type
            indev_drv.read = mouse_read;         //to callback function
	    lv_indev_t * mouse_indev = lv_indev_drv_register(&indev_drv); //register the driver in task queue
	    lv_obj_t * cursor_obj =  lv_img_create(lv_scr_act(), NULL); //create object
	    lv_img_set_src(cursor_obj, SYMBOL_POWER); //set its image
            lv_indev_set_cursor(mouse_indev, cursor_obj); // connect the object to the driver


And your callback function

bool mouse_read(lv_indev_data_t *data)
{
    data->point.x = posx;
    data->point.y = posy;
    data->state = LV_INDEV_STATE_REL;  //state of your mouse button ..press or release..
    return false;  			
}

**Comment by kisvegabor** [comment] 2018-07-30 05:54
Hi,

Your code seems fine. I tested it in `maser` and `dev-5.2` branches too and it worked for me.

I also added this to the test:
```c
 lv_obj_t * label = lv_label_create(lv_layer_sys(), NULL);
 lv_label_set_text(label, "Sys layer");
```

And I got this:
![cursor_test](https://user-images.githubusercontent.com/7599318/43379656-caf529ca-93cd-11e8-9ac3-59051ddf0546.png)


What do you get if you create a label like the above?

**Comment by kisvegabor** [comment] 2018-07-30 05:56
It also works here:
```c
    lv_obj_t * label = lv_label_create(lv_scr_act(), NULL);
    lv_label_set_text(label, "Sys layer");
    lv_obj_set_parent(label, lv_layer_sys());
```

**Comment by kisvegabor** [comment] 2018-08-01 15:28
Try `lv_obj_set_click(cursor_img, false)` to not block if it's on `lv_scr_act()`

Please test this:
1. In `lv_init` (`lv_obj.c`) you will find the creation of sys_layer and top_layer.
2. Change  `lv_obj_set_style(sys_layer, &lv_style_transp_fit);` to `  
    lv_obj_set_style(sys_layer, &lv_style_pretty);`
3. Now the sys_layer should cover everithing a white-graw graient rectangle.

Do you see the rectangle? If not then to debug what's going on you should check this part: https://github.com/littlevgl/lvgl/blob/master/lv_core/lv_refr.c#L343
It starts the rendering of top and sys layers.

**Comment by misterbinny** [comment] 2018-08-01 23:14
The suggested test did not show a rectangle, but simply hid the cursor.  Perhaps the cursor is behaving the way it is unless VDB is used?

From the "lv_refr.c#L343" It looks like that will require Virtual Display Buffering, I am writing directly to a frame buffer in my implementation. 

I would like to get the VDB working, but I think I will have to dig into the code to understand what is going on; but that is off the topic of this thread.

**Comment by kisvegabor** [comment] 2018-08-02 20:52
I checked it and if you don't use VDB then the layers are not refreshed. It's a bug which should be solved by adding these two lines at the end of `static void lv_refr_area_no_vdb(const lv_area_t * area_p)` (lv_refr.c):
```c
    /*Also refresh top and sys layer unconditionally*/
    lv_refr_obj_and_children(lv_layer_top(), area_p);
    lv_refr_obj_and_children(lv_layer_sys(), area_p);
```

**Comment by kisvegabor** [comment] 2018-09-04 05:26
I added the suggested update in `dev-5.2`. If it does not solve your problem please reopen the issue.

**Closed as completed by kisvegabor** 2018-09-04 05:26 UTC
