### ISSUE TITLE
How to create a windows without title?

### ISSUE THREAD

**Issue by mokemars** [lvgl/lvgl#220] opened 2018-04-20 01:21 UTC
I want to creat a window without title.any body can help me?

**Comment by qwert1213131** [comment] 2018-04-20 02:59
You can use lv_page easily.

**Comment by mokemars** [comment] 2018-04-20 03:41
Thanks for you!
i create two windows in the project.if i use page instead of windows.when open the second page in button action,the second page does not cover the first page.the first page object is also in the second page!

**Comment by qwert1213131** [comment] 2018-04-20 08:05
could you show the source code?

**Comment by kisvegabor** [comment] 2018-07-15 15:03
As the solution of @qwert1213131 (use ``lv_page) should work I close this issue.

@mokemars 
If the issue is not solved yet, please post your relevant code snippet here.

**Closed as completed by kisvegabor** 2018-07-15 15:03 UTC
