### ISSUE TITLE
lv_obj_set_free_ptr() There seems to be something wrong with it.

### ISSUE THREAD

**Issue by 3038922** [lvgl/lvgl#853] opened 2019-02-16 15:26 UTC
Ubuntu1804 gcc8.2.0
g++
```
static lv_res_t ssaveAction(lv_obj_t *btn)
{
    int *tempData = static_cast<int *>(lv_obj_get_free_ptr(btn));
    std::cout << "tempData:" << *tempData << std::endl;

    return LV_RES_OK;
}
```
```
    lv_obj_t *aaa = lv_btn_create(displayObj[OBJ_BTNM_SON], nullptr);
    int b = 9900;
    lv_obj_set_free_ptr(aaa, &b);
    lv_btn_set_action(aaa, LV_BTN_ACTION_CLICK, saveAction);
```
![image](https://user-images.githubusercontent.com/33926386/52901739-39c5b780-3242-11e9-948e-3dd5effb8804.png)
This is very, very strange. Is it the relationship between simulators?
All my other buttons are working.

**Comment by embeddedt** [comment] 2019-02-16 15:26
@3038922 Is `b` a local or global variable? It might be going out of scope.

**Comment by 3038922** [comment] 2019-02-16 15:32
b is local.it just a test .
I wanted to pass in a json* class.

**Comment by embeddedt** [comment] 2019-02-16 15:33
@3038922 Please try a global variable and see if the problem persists.

**Comment by 3038922** [comment] 2019-02-16 15:34
![image](https://user-images.githubusercontent.com/33926386/52901825-2ff08400-3243-11e9-9ea2-2e9d19a67925.png)
![image](https://user-images.githubusercontent.com/33926386/52901828-3a128280-3243-11e9-892d-4166ad1961ee.png)
I have so many buttons using `lv_obj_set_free_ptr'. They are all right.

I just wanted to create a save button. Then I found some strange problems.

**Comment by 3038922** [comment] 2019-02-16 15:44
```
int vvvv = 100;
static lv_res_t bbbb(lv_obj_t *btn)
{
    int *aaa = static_cast<int *>(lv_obj_get_free_ptr(btn));
    std::cout << "aaa:" << *aaa << std::endl;
    return LV_RES_OK;
}
```
```
void UserDisplay::createPidTest(lv_obj_t *parent)
{
    createUserTask(TASK_OTHER, pidTask, 100, "PID测试");
    if (displayObj[OBJ_BTNM_SON] == nullptr)
        displayObj[OBJ_BTNM_SON] = lv_tabview_create(parent, nullptr);
    lv_obj_t *asdf = lv_btn_create(displayObj[OBJ_BTNM_SON], nullptr);
    lv_obj_set_free_ptr(asdf, &vvvv);
    lv_btn_set_action(asdf, LV_BTN_ACTION_CLICK, bbbb);
}
```
![image](https://user-images.githubusercontent.com/33926386/52901898-71356380-3244-11e9-9c09-0c697464811a.png)
Global variables can be used.

**Comment by embeddedt** [comment] 2019-02-16 16:03
@3038922 Please describe exactly what the issue is. What behavior are you expecting, and what results are you getting instead?

**Closed as completed** 2019-02-16 16:11 UTC

**Comment by 3038922** [comment] 2019-02-16 16:12
> @3038922 Please describe exactly what the issue is. What behavior are you expecting, and what results are you getting instead?

It's my own C language foundation is not solid. The problem of changing to global variables has been solved. Thank you.
