### ISSUE TITLE
Performance issues with font drawing routines.

### ISSUE THREAD

**Issue by pete-pjb** [lvgl/lvgl#1100] opened 2019-06-12 09:57 UTC
Hi,

Up until yesterday I have been using the Dev-6.0 branch **without the new font routines** and all was working well for me.  I have now integrated the latest Dev-6.0 branch with the new fonts and font drawing routines and I have a very bad performance issue.  I am running LittleVGL on a 666MHz Cortex A9 core so there is no lack of computing power.  The issue becomes particularly prevalent when displaying a multi-line text area containing about 40k bytes of text.  If you move the mouse across the text box the GUI grinds to a halt and the CPU & GUI utilisation hits 100%, if you continue to move the mouse away from the text box everything recovers and returns to normal.  I halted the code during this issue and captured the call stack it always looks the same when ever I halt the code, this is shown in the attached image below:

![Call stack](https://user-images.githubusercontent.com/6610652/59340663-52307500-8cfe-11e9-8dc1-e96fb89993b1.png)

I would expect if you create a text box and load a ~40k byte file and move a mouse pointer over it you will see the issue.  I don't currently work with the simulator so I am unable to provide a simulator code snippet, but I expect with the simulator running on a PC you may not even see the issue as it has far more computing power available.

In general, everything in my GUI has slowed down considerably with the new font routines so I think there may be a need to revisit the implementation?  I am also concerned for projects with small micro's which are potentially going to struggle to render the fonts under some circumstances.  I am very impressed with LittleVGL to date and I can see the enormous amount of work that has been put in to it.  I am sorry to be critical but it is currently unusable for my application as is.  Is there anything I can do to assist with trying to improve the situation?

Kind Regards,

Pete

**Comment by embeddedt** [comment] 2019-06-12 15:18
For some reason I wasn't emailed about this one... strange.

I'll CC @puzrin and @kisvegabor on this as they know the most about how the new system works.

I'll also try it on my STM32F7 today and see if it's slowed down considerably.

Your results show that most CPU time is being spent in `lv_font_get_glyph_dsc` related functions.

**Comment by kisvegabor** [comment] 2019-06-12 15:30
@pete-pjb Please try what happens if you manually set `kern_dsc = NULL` in the generated font.

**Comment by pete-pjb** [comment] 2019-06-12 15:45
Hi @kisvegabor,

Okay I have tried your suggestion using the Roboto_16 built in font and that has made a dramatic improvement to the performance, it is still marginally slower than the previous font code, but it is now usable.  What are the ramifications of not using the Kerning?  It doesn't seem to have upset the spacing of the characters particularly...

Kind Regards,

Pete

**Comment by embeddedt** [comment] 2019-06-12 15:55
> What are the ramifications of not using the Kerning? It doesn't seem to have upset the spacing of the characters particularly.

There are no particular ramifications, besides the fact that it does make the font look nicer to the eyes.

**Comment by pete-pjb** [comment] 2019-06-12 16:11
Hi @embeddedt ,

Actually I can see the difference now and yes there are a few anomalies in the spacing which do make it less appealing to the eye.

I would be interested to hear how your SMT32F7 performs with the kerning enabled, I assume it is running at around 200 Mhz? If so I think it's going to have a really hard time.   I can see why it would be good to have the kerning enabled, but I think most embedded CPU's are going to struggle with the extra load.  Is it worth us all putting our heads together to see if the kerning code can be optimised in some way? 
@kisvegabor - When the text area is being redrawn currently whilst the mouse is passing over it,  am I correct in thinking the entire text of the text area is being processed and not just the lines that are displayed?  This is my perception of what is going on right now but I don't know for sure, if that is the case a major performance could be gained by just processing the lines that are visible, but I can see how this might be a bit of a challenge also.  What are your thoughts?

Kind Regards,

Pete

**Comment by kisvegabor** [comment] 2019-06-12 17:21
@pete-pjb Thank you for the testing. Now the kerning values are searched with "linear search" instead of "binary search". I'll update it tomorrow.

> When the text area is being redrawn currently whilst the mouse is passing over it, am I correct in thinking the entire text of the text area is being processed and not just the lines that are displayed?

Yes, that's correct. The drawing algorithm skips what is possible but it needs to check all letters to find their positions.

**Comment by pete-pjb** [comment] 2019-06-12 18:03
Hi @kisvegabor,

Thank you for your speedy response.  Okay if you want me to test anything on my platform and report back the results, please feel free to ask.

Kind Regards,

Pete

**Comment by kisvegabor** [comment] 2019-06-12 21:02
@pete-pjb 
I've pushed the fix. How does it look like now?

**Comment by embeddedt** [comment] 2019-06-13 01:15
@pete-pjb @kisvegabor 

I've just tested the new font system (very impressed @puzrin!)  on STM32F7 using `lv_test_theme_1`, before and after the kerning update by @kisvegabor.

I found that there was a negligible performance difference once binary search was used. The original version (before binary search) was much slower. Are there any other lookups that could benefit from binary search?

Also, @pete-pjb, do you compile with optimization enabled?

**Comment by puzrin** [comment] 2019-06-13 01:51
> Are there any other lookups that could benefit from binary search?

https://github.com/littlevgl/lv_i18n - translations lookup been done by scan instead of binsearch. Less critical than with kerning, but still worth to fix if someone has time for it.

**Comment by pete-pjb** [comment] 2019-06-13 10:34
Hi,

@embeddedt I have now tested the build with Kerning and optimisation enabled and it certainly improves the situation greatly.

I would like to say thanks to @puzrin & @kisvegabor also, the new 'Kerned' fonts definitely look so much better!

I am still seeing a huge load on the CPU/GUI when moving the mouse over a text area the mouse cursor jumps about 100 pixels at a time when passing over the text area(without optimisation). My current test has about 46k bytes of text in the text area with each line being an average of about 80 characters, it's a log file loaded from an SD-Card which contains timestamped entries with a short textual description of the event logged delimited by a '\n' character.  As the file grows the performance gets worse. I intend to limit the size of my logs by deleting an older event when a new arrives when the file reaches a predefined size but that size is likely to be at least a mega byte which I expect will see me back in the realms of a completely stalled GUI.

Here's some figures I have recorded from testing with a ~46 k byte log file:

**Without optimised** code:
With Dev-6.0 and the old font system the CPU load is around 7% and the GUI load is about 10% when moving the mouse over the text area, pointer is smooth...

With Dev-6.0 and the new font system with Kerning, the CPU load is around 98% and the GUI load is 100% when moving the mouse over the text area, pointer is very jerky...

**With optimised** code:
With Dev-6.0 and the new font system with Kerning, the CPU load is around 84% and the GUI load is about 87% when moving the mouse over the text area, pointer is much smoother...

I realise I might be adding more text to the text area than was originally intended, but if there is a way of improving the performance of the Text Area Object when it contains a lot of text, it would be very useful for me and I would be very grateful!  If you don't think it is a good use of your time then I totally respect that and I will have to look at an alternative method of dealing with my large logs, maybe by introducing on the fly parsing of a large buffer which updates the text area as it is scrolled and just setting a small amount of text at a time from the buffer.

Kind Regards,

Pete

**Comment by kisvegabor** [comment] 2019-06-13 11:21
@pete-pjb 
Very surprising results. Could you check the CPU load with new fonts but `kern_dsc = NULL`?

**Comment by pete-pjb** [comment] 2019-06-13 12:39
Hi @kisvegabor ,

Here are the results...

**Without Optimised Code:**
With Dev-6.0 and the new font system **without** Kerning, the CPU load is around 90% and the GUI load is 94% when moving the mouse over the text area, pointer is smooth..
Slight improvement...

**With optimised code:** -
With Dev-6.0 and the new font system **without** Kerning, the CPU load is around 84% and the GUI load is about 87% when moving the mouse over the text area, pointer is smooth...
No perceivable change...

Kind Regards,

Pete

**Comment by pete-pjb** [comment] 2019-06-13 12:56
Hi @kisvegabor,

I believe the real issue lies back here...
> When the text area is being redrawn currently whilst the mouse is passing over it, am I correct in 
> thinking the entire text of the text area is being processed and not just the lines that are displayed?

>>Yes, that's correct. The drawing algorithm skips what is possible but it needs to check all letters to find their positions.

From what you are saying the font processing is occurring on 46 k bytes of text, but only 14 lines are displayed in the text area, is there a way the processing can be limited to just the lines on display at one time?  I realise that might be a challenge to implement!  Presumably you would need to somehow calculate a pointer to the first character visible on the top left of the text area dependent on the scroll position and then the number of characters to the last character visible at the bottom right of the text area and just process those?  I don't know the code well enough to say how feasible or sensible this is!    Please feel free to shoot me down if I am on the wrong track here! :-)

Kind Regards,

Pete

**Comment by kisvegabor** [comment] 2019-06-13 13:08
> Please feel free to shoot me down if I am on the wrong track here! :-)

If the new fonts introduce a big performance issue then it's very important to investigate it. 

At first look, I can't see how can it be optimized but what bothers me is that it was much faster with the previous fonts. The only obvious change is the introduction of kerning.  With disabled kerning, it should have roughly the same performance than with the old fonts. I played with it to find the bottleneck but with no luck so far. 

Do you have a chance to run some kind of profiling tool to see which function takes so much time?

**Comment by pete-pjb** [comment] 2019-06-13 13:18
Hi @kisvegabor ,

I don't have any profiling set up right now, but I can look into it, I'll see what I can do.

Kind Regards,

Pete

**Comment by embeddedt** [comment] 2019-06-13 14:02
@kisvegabor I think I can run `gprof` on the PC simulator today; that should give us a breakdown of which function is consuming the CPU.

**Comment by pete-pjb** [comment] 2019-06-13 14:31
Hi @kisvegabor and @embeddedt ,

Here is the simple profile output from the Xilinx SDK generated from the JTAG interface...
With Kerning Enabled...
![Profile](https://user-images.githubusercontent.com/6610652/59441275-3b6a4b00-8df0-11e9-892f-605b85e4b2e0.png)


Kind Regards,

Pete

**Comment by pete-pjb** [comment] 2019-06-13 14:40
Hi @kisvegabor and @embeddedt ,

Here is the simple profile output from the Xilinx SDK generated from the JTAG interface...
With Kerning Disabled...

![Profile](https://user-images.githubusercontent.com/6610652/59442111-833da200-8df1-11e9-95ee-3d6e13e5f9cd.png)

Will post one of Dev-6.0 using old fonts shortly...

Kind Regards,

Pete

**Comment by pete-pjb** [comment] 2019-06-13 14:46
Hi @kisvegabor and @embeddedt ,

Here is the simple profile output from the Xilinx SDK generated from the JTAG interface...
Dev-6.0 with old font routines...

![dev6 0-old font](https://user-images.githubusercontent.com/6610652/59442525-4b832a00-8df2-11e9-9ab3-2f406c7b4bfe.png)

Kind Regards,

Pete

**Comment by embeddedt** [comment] 2019-06-13 15:15
It looks like `is_break_char` and `get_glyph_dsc_id` are the functions we should be targetting.

**Comment by pete-pjb** [comment] 2019-06-13 15:27
Hi @embeddedt and @kisvegabor 

It seems to me that it is probable that some functions including `is_break_char()`  and `lv_txt_utf8_get_next()` might be being called more times during the process in the newer version than they were in the old as they are now using more CPU time than previously whilst they remain unchanged between versions?  Like there is some kind of duplication of events going on maybe?

Kind Regards,

Pete

**Comment by kisvegabor** [comment] 2019-06-14 04:30
@pete-pjb Thank you for the profiling charts. It's very useful.
I've pushed some updates, but I'm afraid it won't make much difference. Can you check it again?

@puzrin 
I've played a lot with kerning and realized that now we have 434 kern pair but most of them with very small kern values.

I made some test with some lorem ipsum text and found that with X.2 precision I got ALWAYS then final advanced width (glyph adv_w + kerning). With X.1 precision in 1% of the cases, there was 1 px difference. So I suggest reducing the precision to X.2 or X.1 to reduce the number of kern pair to speed up searching. What do you think?

EDIT:
I made more tests:
With 
X.4: with 434 pairs bin search runs 8-9 times
X.2: 188 pairs remain, bin search runs 7-8 times
X.1: 106 pairs remain, bin search runs 6-7 times
X.0: 32 pairs remain, bin search runs 5-6 times

X.1 would mean 20-25% less iteration. If I needed to choose between speed and a minor gain in quality in  1% of the cases I'd definitely choose performance. 

So do you agree to reduce the precision to X.1? At least for the lvgl writer
.

**Comment by pete-pjb** [comment] 2019-06-14 08:56
Hi @kisvegabor ,

Here is a profile of current Dev-6.0 (Kerning enabled) with mouse passing over text box containing ~50K Bytes of text.

![Profile](https://user-images.githubusercontent.com/6610652/59495729-dd894200-8e87-11e9-8e52-ebbc8021f92e.png)

It seems to have increased the CPU load but the log file is a bit bigger so probably similar.

In my previous post:

> It seems to me that it is probable that some functions including `is_break_char()` and `lv_txt_utf8_get_next()` might be being called more times during the process in the newer version than they were in the old as they are now using more CPU time than previously whilst they remain unchanged between versions? Like there is some kind of duplication of events going on maybe?

I may not have made my thinking clear, it's hard to describe!   I was insinuating may be the `lv_refr_obj()` function is for some reason being called more times than necessary in the new code, if that makes sense? Why would the amount of CPU time required for is_break_char() and other supporting functions increase when they appear to be the same code on both versions doing the same thing for same amount of characters?  The only explanation I can come up with in my mind right now is they are being called more times than previously do you not agree?  Do you see my thinking?
I am going to attempt to find a way to monitor how many times `lv_refr_obj()` is called on the text area after a mouse movement to try and pin this down....

Kind Regards,

Pete

**Comment by kisvegabor** [comment] 2019-06-14 09:06
> It seems to have increased the CPU load.

Thank you for the feedback. I'll continue the investigation, I've found that font converter generates a different type of kerning (classes instead of pairs) for `montserrat` font. I attached the font generated with montserrat (named it to "roboto" for easy replacement).
[lv_font_roboto_16.c.zip](https://github.com/littlevgl/lvgl/files/3289895/lv_font_roboto_16.c.zip)

For me, it resulted in a huge improvement.

> I am going to attempt to find a way to monitor how many times lv_refr_obj() is called on the text area after a mouse movement to try and pin this down....

I don't think it's the case, but let's check it to be sure. 
 Thank you in advance

**Comment by puzrin** [comment] 2019-06-14 09:12
@kisvegabor

> So do you agree to reduce the precision to X.1? At least for the lvgl writer

IMO it's very bad idea to diverge data for such small gain.

- You could demand option to force Format3 (table) for kerning, with cost of ~ 100-200 bytes increase for ASCII (righ now - just increase dumped glyphs count)
- You could cache last `get_glyph_das_id()` (if not yet), because it's called twice on each string scan (for left and right neighbours)

Also, as far as i understand, that's not critical chain. Problem is that long strings are not limited effectively.

**Comment by pete-pjb** [comment] 2019-06-14 09:24
@kisvegabor 

Just another quick note, I have also observed today, that the same issue is present when the mouse passes over a roller containing ~2000 items, I know this seems a lot of items, but with the new call backs in V6.0 I have implemented a text search and you can type letters from the keyboard and the roller scrolls to the the entry that matches the typed string in real-time as you type which makes the huge list much more usable....

Kind Regards,

Pete

**Comment by kisvegabor** [comment] 2019-06-14 09:38
@puzrin 
> You could cache last get_glyph_das_id() (if not yet), because it's called twice on each string scan (for left and right neighbours)

I buffer the last letter + glyph but it didn't help so much.

The critical thing is the lot of kerning value searches. Forcing format=3 is a good idea if @pete-pjb confirms that it makes rendering faster. In this case, I would make it default for the online converter.

I believe moving to X.2 is a good idea for 10-20% faster search and loosing almost nothing visually.

**Comment by pete-pjb** [comment] 2019-06-14 09:40
Hi @kisvegabor ,

The montserrat font does work slightly better but the CPU/GUI load is still extremely high the mouse movement is smoother but still a bit jerky...

Kind Regards,

Pete

**Comment by kisvegabor** [comment] 2019-06-14 09:53
@pete-pjb What is CPU load now without kerning and with optimization?

**Comment by puzrin** [comment] 2019-06-14 10:03
> The critical thing is the lot of kerning value searches. Forcing format=3 is a good idea if @pete-pjb confirms that it makes rendering faster. In this case, I would make it default for the online converter.
> 
> I believe moving to X.2 is a good idea for 10-20% faster search and loosing almost nothing visually.

"Critical chain" term means "most slow thing in whole system". In this case, kerning extract is NOT critical chain. Because problem is in long strings processing, when you process 10x more chars than needed. It's the basics of optimisations - always fix worst thing first.

When you have loss of 10x, and suggest to diverge data of 1.25x benefits that sounds horrible :). Because "breaks" 2 things at once - optimizations order and design/architecture :)

**Comment by kisvegabor** [comment] 2019-06-14 10:07
You are right, however, it worked fine with the old fonts. So I need to assume that there is a problem with the fonts somehow.

Regarding the critical chain: from [the last chart](https://github.com/littlevgl/lvgl/issues/1100#issuecomment-502029066) it's clear that searching takes the 45% of CPU time. So we need to optimize there.

**Comment by puzrin** [comment] 2019-06-14 10:18
> Regarding the critical chain: from [the last chart](https://github.com/littlevgl/lvgl/issues/1100#issuecomment-502029066) it's clear that searching takes the 45% of CPU time. So we need to optimize there.

I don't agree both with used measurement and with conclusion.

1. Measurement should be "correct". Refered one measures local things only, and does not take into account "real" problem - long strings in textarea.
2. If something local takes some resources, that does not means it should be optimized. Especially, via hacks.

I understand, you have time constrains. From this point of view, is see compromise in "not adding new kludges". In other words... forcing "Format3" is your chance to postpone problem without using "bad" practices :).

**Comment by kisvegabor** [comment] 2019-06-14 10:29
> Measurement should be "correct". Refered one measures local things only, and does not take into account "real" problem - long strings in textarea.

That's true.  However, because of word wrap, I can't see other solution to know the characters positions than checking all of them. So I see no way to optimize this part. 

We have chosen X.4 arbitrarily. It's not sacred. If it's overkill because the last 2 bits don't really affect the output, we can change it. It's not a hack.

**Comment by kisvegabor** [comment] 2019-06-14 10:43
@pete-pjb Can you add a chart when the "montserrat" font is used? There is no `bsearch` in it so I'm very curious about what causes the high CPU usage then.

**Comment by puzrin** [comment] 2019-06-14 10:49
> However, because of word wrap, I can't see other solution to know the characters positions than checking all of them. So I see no way to optimize this part.

This task is solved somehow in text editors. The most obvious approach is to remember range of visible area. That will not help with text change, but will help with multiple redraws on mouse move.

> We have chosen X.4 arbitrarily. It's not sacred.

Not arbitrary. I've checked first that data will not be lost (pairs will not disappear).

> If it's overkill because the last 2 bits don't really affect the output, we can change it. It's not a hack.

I'd say, that's your personal opinion, and if you don't see something, that does not mean other don't see difference :). I can suggest you more formal criteria - check combinations of width+kerning and where rounding is changed. Then it will be more clear where to look.

Under hack i mean diverge from "mainstream". In my eyes proposed diverge is significant. Also, i think data should have some "reserve" to not depend on subjective opinion.

PS. Anyway, i think switch to Format3 (table of classes) is optimal for current moment.

**Comment by pete-pjb** [comment] 2019-06-14 11:15
Hi @kisvegabor ,

I have tested the calls to lv_refr_obj() and lv_refr_obj_and_children() for the new and the old font implementation and you are correct, I was wrong...  It is the same.  I made the UART send out 'ro ' and 'roc ' respectively for the two functions when they are called.  Here are the results if I change the value of the mouse coordinates using the eclipse expression tab whilst the programs were running for the two builds...

Dev-6.0 new font system...
roc ro ro ro ro ro roc ro roc ro ro

Dev-6.0 old font system 
roc ro ro ro ro ro roc ro roc ro ro 

So we can eliminate that possibility...

Also here's a screenshot of the scenario...
![logscreenshot](https://user-images.githubusercontent.com/6610652/59505659-f997de00-8e9d-11e9-832d-76aab2209203.png)

To date I really haven't delved deeply into the LittleVGL code so I don't have a complete picture of how it works in my mind...  I think I would now like to study it further and try and help with resolving this issue.  It seems to me a good solution might be, albeit probably quite challenging to implement, would be to limit the font processing to just the visible area of text in the text area or roller?  This would eliminate all concerns with text sizes in text area and list sizes in rollers....  Is it possible to achieve or am I speaking out of turn here?  :-)

Kind Regards,

Pete

**Comment by pete-pjb** [comment] 2019-06-14 11:27
Hi @kisvegabor ,

Please find following profile as requested for "montserrat" font:

![Profile](https://user-images.githubusercontent.com/6610652/59506240-aaeb4380-8e9f-11e9-865e-2d71eb755f2a.png)

Kind Regards,

Pete

**Comment by puzrin** [comment] 2019-06-14 11:37
@pete-pjb 

>  It seems to me a good solution might be, albeit probably quite challenging to implement, would be to limit the font processing to just the visible area of text in the text area or roller? This would eliminate all concerns with text sizes in text area and list sizes in rollers.... Is it possible to achieve or am I speaking out of turn here? :-)

I'd say, it worth to investigate how task of words wrap and text update is solved in text editors. Because there are many pitfails and there should be well known solutions with predictable behaviour.

For example, VSCode and Atom are written in javascript (sic!) and are still ok with big texts (and that's not because desktop cpu-s are fast).

**Comment by pete-pjb** [comment] 2019-06-14 11:59
@puzrin 

Thank you for the clues, I haven't really done much embedded GUI work in the past so it's a steep learning curve for me... Being quite old ;-) my previous product developments have mostly been managed by Menu based VT100 CLI interfaces over Telnet/SSH or RS232, and SNMP with the occasional web interface.

I will have a look around and see if I can find out anything useful....

Kind Regards,

Pete

**Comment by puzrin** [comment] 2019-06-14 12:22
Note, "big text effective store and edit" is not specific to embedded. That's a general algorythmic problem. On desktop, if you open 10Mb text file, you will have to solve exactly the same problems as on embedded with 100k string.

Also, this problem is not about GUI, but about effective data store/extract/update.

**Comment by embeddedt** [comment] 2019-06-14 13:20
It seems to me that the two problems here are that:

* Calculating information about characters takes longer than it did in 5.3.
* These calculations are performed for every letter, regardless of whether it is visible on screen.

In order to make the font system faster, we have to fix at least one of those two issues.

@puzrin says that we should deal with the underlying architectural issue, which is that possibly unnecessary calculations are being performed every time the mouse moves.

@kisvegabor points out that the previous version worked fine, because the calculations were negligible.

Both sides appear to be technically correct.

In a case like this, my strategy would be to *try* fixing whichever problem is easier to solve from a developer's point of view. If it ends up solving the performance issue, great! If not.. we all learned something :)

We're not aiming for absolute design perfection here. We are just looking to ramp up the font performance a bit.

In my opinion - optimizing the calculations themselves sounds simpler than handling range checks, etc. But I'm not an expert on font metrics (or on range checking) so maybe I'm off my rocker.

Since performance was never a major issue in previous versions, I suggest we make the new font system as fast as the previous versions instead of trying to modify LittlevGL itself to work around performance problems in the new font system.

**Comment by puzrin** [comment] 2019-06-14 13:36
@embeddedt there is trivial temporary solution - change kerning format to F3, until can fix long strings (text area) properly. It's easy and does not add unfixable side effects in long term. Effect will be more big than from tricks with kerning data precision.

> Since performance was never a major issue in previous versions, I suggest we make the new font system as fast as the previous versions instead of trying to modify LittlevGL itself to work around performance problems in the new font system.

Just increase text size in 10x, scroll text to the end and you will get exactly the same problem in old font system.

Key point is, that kerning pairs bin search cause limited slow down, but textarea can cause unlimited slowdown (with text increase) due too simple design.

**Comment by kisvegabor** [comment] 2019-06-14 14:22
> It seems to me that the two problems here are that:
- Calculating information about characters takes longer than it did in 5.3.
- These calculations are performed for every letter, regardless of whether it is visible on screen.

It would be the best to improve both. :smile: 

Forcing "format 3" for faster searching is a good idea. 10-20% performance gain is surely worth 100-200 bytes. So @puzrin could so add this option?

Finally, I've found a way to optimize label drawing. As we already figured it out the problem is that it takes a lot of time get to the first visible letter. I managed to implement a "hint" system which caches some info to speed up this process.

It works like this:
1. Buffer the index and the 'y' coordinate of a line at `y = -1000` coordinate.
2. Start the checking of letters from the buffered index and `y` coordinate.
3. Make the hint invalid if the label moved > 900 px compared to the coordinates when the hint was saved.

I've tested it on STM32F429 Discovery with 40K text and it's was very smooth. The scrolling lags once when 900 px is scrolled but it's not really disturbing.

I added a function to disable "cursor navigation by click on" the text area because it also requires the same calculation. The function is `lv_ta_set_cursor_click_pos(ta, false)`

The hint is not used if the label is smaller than 1000 px so it shouldn't break existing things.   

(The 1000 and 900 numbers are just examples to make it easier to understand.)

The update is in the `hint` branch. Can you test it?

**Comment by puzrin** [comment] 2019-06-14 14:25
> Forcing "format 3" for faster searching is a good idea. 10-20% performance gain is surely worth 100-200 bytes. So @puzrin could so add this option?

Yes boss :)!

Any ideas about option name?

**Comment by kisvegabor** [comment] 2019-06-14 14:31
Thank you! :blush:

> Any ideas about option name?

`--force-kern-class`?

**Comment by puzrin** [comment] 2019-06-14 14:34
> `--force-kern-class`?

Ok if nothing else.

Seems not very clear without additional descriptions.

**Comment by kisvegabor** [comment] 2019-06-14 14:39
This description?
`Use kern classes instead of pairs (might be larger but faster)`

**Comment by embeddedt** [comment] 2019-06-14 14:40
`--force-format3`

**Comment by puzrin** [comment] 2019-06-14 14:42
@kisvegabor I mean, it wirth try to invent alternate option name, if possible. If not - i will use one you sugjested before.

@embeddedt 

> `--force-format3`

i guess `--force-kern-format3` then. Because CMAP table also has subformats.

**Comment by embeddedt** [comment] 2019-06-14 14:44
@puzrin Perfect!

**Comment by kisvegabor** [comment] 2019-06-14 14:46
IMO format3 is less intuitive but it's ok for me. It should be clear from the description. anyway.

**Comment by puzrin** [comment] 2019-06-14 14:49
i agree `--force-kern-class` may be more clear, but in general - it's not clear why is this needed at all.

**Comment by puzrin** [comment] 2019-06-14 14:50
`--force-fast-kern` - not perfect, but explains what i mean.

**Comment by puzrin** [comment] 2019-06-14 14:51
`--force-fast-kern-format`

**Comment by puzrin** [comment] 2019-06-14 15:03
`--fast-kern-format` (word `force` excess)

**Comment by embeddedt** [comment] 2019-06-14 15:04
@puzrin I feel that `force` gives a better impression of the tradeoff.

**Comment by pete-pjb** [comment] 2019-06-14 15:21
Hi @kisvegabor ,

cc: @puzrin , @embeddedt 

Here is a profile of the Lvgl-hint branch...  This is much more usable!

![Profile](https://user-images.githubusercontent.com/6610652/59519578-0fb69600-8ec0-11e9-8423-a81aff2387fd.png)

I think you have cracked it Gabor - Very well done, you are the man! :-)

It also appears to have fixed the mouse over roller with large list...

Kind Regards,

Pete

**Comment by embeddedt** [comment] 2019-06-14 15:35
@kisvegabor Great! It looks like it performs a bit better on STM32 as well.

I fixed a minor bug: https://github.com/littlevgl/lvgl/commit/a92ffe7cde646c50ebfa8c9c29ce1cc4cfd68abf

**Comment by puzrin** [comment] 2019-06-14 16:51
Try https://github.com/littlevgl/lv_font_conv/tree/fast_kern, `--force-fast-kern-format`.

Tell me final option name please, and i will merge to master.

**Comment by puzrin** [comment] 2019-06-14 17:00
FYI: Average worst case from real world ~ 300 bytes loss.

**Comment by kisvegabor** [comment] 2019-06-15 05:07
@pete-pjb 
> I think you have cracked it Gabor 

Huh, awesome! I was a little bit desperate that we will evolve backward. :sweat_smile: But finally it solves the root of the issue and not a temporal solution. Now LittlevGL can effectively handle text with arbitrary length. Which is, I suppose, a quite unique thing among the embedded GUI libraries.

> It also appears to have fixed the mouse over roller with large list...

Great! 

@embeddedt 
> Great! It looks like it performs a bit better on STM32 as well.

Is it only a little better? With 40k letters it was useless earlier and now perfect for me. Is it still laggy for you?

> I fixed a minor bug: a92ffe7

Than you!


@puzrin 
> Try https://github.com/littlevgl/lv_font_conv/tree/fast_kern, --force-fast-kern-format.
Tell me final option name please, and i will merge to master.

I like `--force-fast-kern-format`

**Comment by kisvegabor** [comment] 2019-06-15 15:22
@BrianPugh When I immersed in the optimization of text line processing I found `lv_txt_get_next_line` quite difficult to understand and optimize because of the  `LV_TXT_LINE_BREAK_LONG_...` related things. After some thinking, I concluded that this feature is not so commonly used and for simplicity, I reverted the original algorithm. I hope you don't mind. If this feature would be required later we can use your implementation again. 

---

I merged `hint` to `dev-6.0` with the new fonts. And added `LV_LABEL_LONG_TXT_HINT` to `lv_conf.h` to enable the new feature.

**Comment by BrianPugh** [comment] 2019-06-16 21:55
@kisvegabor I could refactor that code if readability is the primary concern. I definitely need this feature, but I could also just use my own customized fork.

**Comment by kisvegabor** [comment] 2019-06-16 22:19
@BrianPugh 
>  I could refactor that code if readability is the primary concern.

That would be great! 

There are some tricks with `letter`, `letter_next`, `i` and `i_next` [here](https://github.com/littlevgl/lvgl/blob/dev-6.0/src/lv_misc/lv_txt.c#L163-L165). This part should be left unchanged (It looks simple but it's quite tricky because of `lv_txt_encoded_next`).

**Comment by BrianPugh** [comment] 2019-06-17 16:11
cool! working on this now, should be ready in a few days

**Comment by BrianPugh** [comment] 2019-06-23 23:21
@kisvegabor see #1115

**Comment by kisvegabor** [comment] 2019-06-25 16:05
I merged to update of @BrianPugh so I close this issue.

Thank you all for the ideas and the investigation on this issue!

**Closed as completed by kisvegabor** 2019-06-25 16:05 UTC
Labels: 🐞 Bug
