### ISSUE TITLE
Creat obj solid

### ISSUE THREAD

**Issue by autoprog** [lvgl/lvgl#882] opened 2019-02-21 13:34 UTC
Hi,
how to creat simple obj solid with border, and change color in real time.

![obj_solid](https://user-images.githubusercontent.com/5191545/53172436-1beeae80-35c4-11e9-9464-a4c5b96c46c7.png)

thanks,
Carlos.

**Comment by seyyah** [comment] 2019-02-21 14:19
You may use `lv_canvas` [1,2].

Example: `lv_test_canvas_2()`

![image](https://user-images.githubusercontent.com/263237/53175344-d0a4c200-35fc-11e9-9c77-9ab32e1fffa6.png)

## :clipboard: Reference
1. https://github.com/littlevgl/lvgl/blob/master/lv_objx/lv_canvas.c
2. https://github.com/littlevgl/lv_examples/blob/master/lv_tests/lv_test_objx/lv_test_canvas/lv_test_canvas.c

**Comment by embeddedt** [comment] 2019-02-21 15:54
@autoprog Another option is to keep adjusting the style of the object and then set it again using `lv_obj_set_style`.

**Comment by autoprog** [comment] 2019-02-28 20:16
Hi, 
testd lv_creat obj + lv_set_style = ok

thanks,
Carlos.

**Comment by embeddedt** [comment] 2019-02-28 20:22
@autoprog If the issue is solved please close it.

**Closed as completed** 2019-02-28 20:26 UTC
