### ISSUE TITLE
lv_demo_printer hit dropdown list, program will crash.

### ISSUE THREAD

**Issue by ftts12** [lvgl/lvgl#1787] opened 2020-09-11 15:41 UTC
static lv_res_t lv_dropdown_signal(lv_obj_t * ddlist, lv_signal_t sign, void * param)
{  
  else if(sign == LV_SIGNAL_GET_STATE_DSC) {
        lv_get_state_info_t * info = param;
        if((info->part == LV_DROPDOWN_PART_LIST) ||
           (info->part == LV_DROPDOWN_PART_SCROLLBAR) ||
           (info->part == LV_DROPDOWN_PART_SELECTED) )
		{
			if (ext->page != NULL)//add check page 
			{
				info->result = lv_obj_get_state(ext->page, LV_PAGE_PART_BG);
			}
            
        }
    }

**Comment by ftts12** [comment] 2020-09-11 15:42
ext->page need check if it is NULL.

**Comment by embeddedt** [comment] 2020-09-11 18:23
Looks like a duplicate of #1782. Please try with the latest branch.

**Comment by kisvegabor** [comment] 2020-09-14 08:41
I close it as duplicated.

**Closed as completed by kisvegabor** 2020-09-14 08:41 UTC
Labels: 🔁 Duplicated
