### ISSUE TITLE
LVGL Image Converter overlays a blue tint. Same as #1692

### ISSUE THREAD

**Issue by zhuang0393** [lvgl/lvgl#1873] opened 2020-10-29 02:36 UTC
I encountered the same problem：
![p1](https://user-images.githubusercontent.com/4112322/97519530-5da83d00-19d4-11eb-972b-dd2c41b8ae12.png)

Resulting Image on pc screen
![C3128AE6-330D-4904-B864-0C16F2BEA877](https://user-images.githubusercontent.com/4112322/97519571-67ca3b80-19d4-11eb-9aa4-3d75f2942aa1.png)

The C array : (blue byte is not 0x00 but 0x97)
#if LV_COLOR_DEPTH == 32
/Pixel format: Blue: 8 bit, Green: 8 bit, Red: 8 bit, Alpha: 8 bit/
0x97, 0x00, 0x00, 0xff, 0x97, 0x00, 0x00, 0xff, 0x97, 0x00, 0x00, 0xff, 0x97, 0x00, 0x00, 0xff, 0x97, 0x00, 0x00, 0xff, 0x97, 0x00, 0x00, 0xff,

imageconverter params:
![4762B86A-689D-4df7-B153-3B4270D424E8](https://user-images.githubusercontent.com/4112322/97519602-71ec3a00-19d4-11eb-860a-6b41aa5636f7.png)

**Comment by embeddedt** [comment] 2020-10-29 12:38
Duplicate of #1692

See my response there.

**Closed as completed by embeddedt** 2020-10-29 12:38 UTC
