### ISSUE TITLE
Animation curruption in the lastest master branch/printer demo

### ISSUE THREAD

**Issue by barbiani** [lvgl/lvgl#1724] opened 2020-08-14 05:17 UTC
I have just pulled the last commit and found that the animated icons are showing some corruption when clicked or fading in/out.

I do not know when it happened because it has been a while since I tested it in a VS/SDL environment.

It is the plain printer demo with the windows SDL driver code from the other repository.

Anyone else saw these?

Fading in...
![image](https://user-images.githubusercontent.com/7387556/90216032-da634c00-ddd3-11ea-98b1-72dcea04b263.png)

Clicked...
![image](https://user-images.githubusercontent.com/7387556/90216051-e222f080-ddd3-11ea-88bb-70f6b5d5a63e.png)

**Comment by kisvegabor** [comment] 2020-08-14 05:22
With the Eclipse SDL simulator it works fine.
Can someone confirm that it's working in Eclipse?

**Comment by embeddedt** [comment] 2020-08-14 10:42
I will test it in a few hours.

**Comment by barbiani** [comment] 2020-08-17 04:41
Might be only here but:

Setting to
#define LV_COLOR_DEPTH     32
#define LV_COLOR_SCREEN_TRANSP    1

Turns to a semi transparent red area during the animation. At least no more corruption.

I am using SDL (800x600) with two 32 lines buffers.

![image](https://user-images.githubusercontent.com/7387556/90357751-6d95bf00-e02a-11ea-8e4f-df3e1af1b427.png)

**Comment by sveniv** [comment] 2020-08-19 09:56
I had the same problem, but reversing the change made by commit 28807b6a77b96ffcb144bc433f932a2f0b67a36e fixed it for me.
(I also tried commenting out the line, but that also gave the same glitches.)

I'm running this on Linux and `sdl2-config --version` returns `2.0.8` if that helps.

**Comment by sveniv** [comment] 2020-08-20 15:32
I removed the old problematic `lv_sim_eclipse_sdl` project from eclipse, cloned a fresh copy from github and imported that into Eclipse. The printer demo now works for me without any changes other than un-commenting/commenting the function calls for the examples in `main.c`. I suspect that I had made some changes to the project configuration in Eclipse that caused it.

**Comment by kisvegabor** [comment] 2020-08-20 20:00
Hmm, very strange. Anyway, good to hear it works with a fresh copy. 

I close this issue then.

**Comment by tjstyle** [comment] 2020-08-30 05:20
![glitch](https://user-images.githubusercontent.com/463152/91651717-41624f80-eaba-11ea-8615-59302ec3664c.gif)

@kisvegabor I also have the same problem with the latest master branch using STM32 hardware and reversing the https://github.com/lvgl/lvgl/commit/28807b6a77b96ffcb144bc433f932a2f0b67a36e commit the problem is gone.

**Comment by kisvegabor** [comment] 2020-08-31 09:23
It seems LVGL thinks that the images cover the area while they are transparent. However, it's checked [here](https://github.com/lvgl/lvgl/blob/694d9eff199ab9725b325e752003a72bb911e936/src/lv_widgets/lv_img.c#L605).

Can you try what happens if you add `return LV_DESIGN_RES_NOT_COVER;` immediately in `if(mode == LV_DESIGN_COVER_CHK)` .

**Comment by tjstyle** [comment] 2020-08-31 15:17
confirmed, using `return LV_DESIGN_RES_NOT_COVER;` problem is gone

**Comment by kisvegabor** [comment] 2020-09-01 07:38
Thanks for testing!

I've pushed a fix to master. Can you try it?

**Comment by tjstyle** [comment] 2020-09-01 17:43
Tested, the latest master solve the problem, thanks!

**Comment by kisvegabor** [comment] 2020-09-01 19:06
Great! Thank you for the feedback!

**Closed as completed by kisvegabor** 2020-09-01 19:06 UTC
