### ISSUE TITLE
Plan for the next version

### ISSUE THREAD

**Issue by jason-sophia** [lvgl/lvgl#1200] opened 2019-09-23 11:53 UTC
hi~
Could you tell us your plan for the next version? 
Which features will be supported？
and when will the new version be released?

**Comment by embeddedt** [comment] 2019-09-23 12:39
Duplicate of #1132

**Comment by embeddedt** [comment] 2019-09-23 12:39
----------------------
We use GitHub issues for development related discussions.
Please use the [forum](https://forum.littlevgl.com/) to ask questions.

It's possible to sign in to the forum with your GitHub account... you don't need to make a separate account.

**Closed as completed by embeddedt** 2019-09-23 12:39 UTC
