### ISSUE TITLE
issue for setting critical value of gauge

### ISSUE THREAD

**Issue by ZhaoQiang-b45475** [lvgl/lvgl#1648] opened 2020-07-09 03:22 UTC
Hi, 
I meet an issue, when setting critical value to a value between two adjacent labels, the arc and the scale color are unpredictable, please refer to the images attached, I set the critical as 124, 126, 180 and 121. is it a issue.

<img width="202" alt="set124" src="https://user-images.githubusercontent.com/22284222/86993065-9af28000-c1d5-11ea-989c-e4ee1a08a88a.PNG">
<img width="200" alt="set126" src="https://user-images.githubusercontent.com/22284222/86993069-9cbc4380-c1d5-11ea-9dba-7267a2fd074c.PNG">
<img width="206" alt="set180" src="https://user-images.githubusercontent.com/22284222/86993070-9d54da00-c1d5-11ea-87fc-bb79b02959b8.PNG">
<img width="204" alt="set121" src="https://user-images.githubusercontent.com/22284222/86993072-9ded7080-c1d5-11ea-911b-91204b83c8ad.PNG">

**Comment by kisvegabor** [comment] 2020-07-10 13:04
Hi,

I pushed a fix to master. Could you test it?

**Comment by ZhaoQiang-b45475** [comment] 2020-07-14 08:25
Thank you! I will try

**Comment by kisvegabor** [comment] 2020-08-03 07:39
As there was no activity here for a while  I suppose the issue is solved.

If it's not working feel free the comment here and reopen this issue.

**Closed as completed by kisvegabor** 2020-08-03 07:39 UTC
