### ISSUE TITLE
how to swipe down  son obj  to father obj

### ISSUE THREAD

**Issue by rongyunxiang** [lvgl/lvgl#2192] opened 2021-04-12 03:08 UTC
### Examples and cases

 father page: obj
 lv_obj_t son_obj = lv_cont_creat(obj, NULL);
 lv_obj_t son_a = lv_cont_creat(obj, NULL);
 lv_obj_t son_b= lv_cont_creat(obj, NULL); 
...

lv_obj_set_event_cb(son_obj , callback);

void callback()
{
 ...
goto page (son_obj);
lv_obj_del_async(obj);
...
}

son obj page:
lv_obj_set_event_cb(obj, gestureCapture);

### Suggested solution
I tried to  not set full screen:
 lv_obj_align(obj, NULL, LV_ALIGN_IN_TOP_LEFT, 0, 10);  
It  works better ,but when I use mouse to pull down from y 10-50 , it doesn't work

**Comment by rongyunxiang** [comment] 2021-04-13 06:15
solved

**Comment by embeddedt** [comment] 2021-04-14 14:50
Since the issue is solved I will close it.

**Closed as completed by embeddedt** 2021-04-14 14:50 UTC
