### ISSUE TITLE
textarea can not cancel selection when click the area out of the inputed chars.

### ISSUE THREAD

**Issue by incity** [lvgl/lvgl#1812] opened 2020-09-23 12:57 UTC
![image](https://user-images.githubusercontent.com/7846605/94014897-c05b5700-fdde-11ea-8880-67d52666cbe3.png)

click area 2 can not cancel text selection.

by the way, how can i delete the selected chars?

**Comment by kisvegabor** [comment] 2020-09-27 13:01
How did you try to cancel it?

**Comment by incity** [comment] 2020-09-28 01:08
@kisvegabor click area 2 should cancel the selection, right?

**Comment by kisvegabor** [comment] 2020-09-30 06:51
No, it shouldn't. The selection is managed by the user. 

However, I agree that the area can be improved to make these things automatic.

**Comment by kisvegabor** [comment] 2020-10-07 10:25
I close this issue because it's not bug but the intended behavior.

If you have remarks about this topic feel free to comment here and reopen the issue.

**Closed as completed by kisvegabor** 2020-10-07 10:25 UTC
